import random

EASY = [
    "the", "be", "to", "of", "and", "a", "in", "it", "you", "that",
    "he", "was", "for", "on", "are", "but", "not", "at", "by", "i",
    "his", "they", "her", "she", "or", "we", "my", "one", "all", "do",
    "if", "an", "up", "so", "no", "go", "me", "him", "as", "is",
    "has", "us", "am", "our", "who", "its", "had", "how", "get", "got",
    "did", "can", "may", "say", "see", "new", "now", "way", "use", "two",
    "set", "run", "day", "big", "old", "end", "put", "own", "too", "any",
    "ask", "try", "let", "far", "add", "low", "few", "off", "man", "men",
    "top", "eye", "air", "cut", "hot", "red", "eat", "sat", "bed", "six",
    "ten", "yet", "bit", "dog", "sun", "sit", "boy", "age", "car", "job",
    "win", "fit", "cup", "map", "box", "arm", "art", "act", "hat", "key",
    "lot", "pay", "sea", "war", "law", "oil", "dry", "lay", "yes", "fun",
    "did", "ran", "met", "led", "hit", "son", "bad", "die", "fly", "sky",
    "tax", "ice", "mix", "fix", "gap", "bag", "leg", "tip", "lip", "gas",
    "bar", "pen", "mud", "log", "fan", "van", "cow", "raw", "pig", "dot",
    "row", "pan", "pin", "nor", "pop", "rid", "tie", "jam", "joy", "sum",
    "dam", "dug", "fog", "fur", "gut", "hen", "hut", "inn", "jar", "jug",
    "kit", "lid", "mob", "nap", "net", "nod", "nun", "oak", "odd", "ore",
    "pad", "peg", "pit", "pod", "pub", "rag", "ram", "rat", "rib", "rod",
    "rug", "rut", "sap", "shy", "sin", "sip", "sob", "sow", "spy", "tab",
    "tag", "tan", "tap", "tar", "tin", "toe", "ton", "toy", "tub", "tug",
    "vet", "vow", "web", "wig", "wit", "woe", "yam", "zap", "zip", "zoo",
    "this", "from", "with", "have", "will", "been", "what", "when", "your",
    "were", "some", "them", "than", "each", "make", "like", "long", "look",
    "time", "very", "just", "know", "take", "come", "more", "most", "only",
    "over", "such", "also", "back", "work", "year", "give", "well", "good",
    "high", "last", "keep", "same", "find", "here", "many", "much", "then",
    "hand", "both", "does", "home", "even", "side", "name", "show", "help",
    "part", "life", "live", "turn", "move", "play", "next", "read", "head",
    "tell", "must", "call", "want", "need", "line", "kind", "word", "land",
    "sure", "real", "feel", "hold", "open", "late", "hard", "mind", "best",
    "door", "seem", "free", "face", "city", "tree", "talk", "food", "fish",
    "rain", "fire", "dark", "cold", "blue", "step", "walk", "stop", "pick",
    "ball", "song", "deep", "mark", "fill", "plan", "half", "draw", "east",
    "fast", "rock", "wait", "pull", "boat", "bird", "care", "mile", "warm",
    "hill", "iron", "gold", "moon", "star", "ship", "bear", "deer", "gray",
    "cool", "drop", "fall", "farm", "fish", "wood", "wide", "wild", "rose",
    "ring", "ride", "root", "salt", "sand", "seed", "snow", "soft", "soil",
    "soul", "wind", "bone", "burn", "camp", "card", "coat", "cook", "copy",
    "deal", "dust", "earn", "edge", "fair", "flag", "flat", "flow", "fool",
    "gift", "glad", "grow", "hang", "hate", "hide", "hunt", "jump", "kick",
    "king", "kiss", "knee", "lake", "leaf", "lean", "lift", "list", "load",
    "lock", "lord", "loss", "luck", "mail", "mass", "meat", "milk", "miss",
    "mood", "neck", "nose", "note", "pack", "page", "pair", "pale", "palm",
    "park", "path", "peak", "pink", "pool", "pour", "pray", "pure", "push",
    "race", "rank", "rare", "rest", "rice", "rich", "roll", "roof", "rope",
    "rush", "safe", "sail", "save", "seat", "seek", "sell", "shot", "shut",
    "sign", "sing", "sink", "slip", "slow", "snap", "sock", "sort", "spot",
    "stem", "stir", "suit", "swim", "tail", "tall", "tape", "task", "tear",
    "test", "thin", "till", "tool", "tour", "trap", "tube", "twin", "vast",
    "vote", "wake", "wall", "wash", "wave", "weak", "wear", "week", "whom",
    "wine", "wing", "wire", "wise", "wood", "wrap", "yard", "zone",
]

MEDIUM = [
    "about", "after", "again", "being", "below", "bring", "build", "carry",
    "cause", "chain", "chair", "cheap", "check", "chief", "child", "china",
    "chose", "civil", "claim", "class", "clean", "clear", "climb", "clock",
    "close", "coach", "coast", "color", "count", "court", "cover", "crash",
    "crazy", "cream", "crime", "cross", "crowd", "dance", "death", "doubt",
    "dozen", "draft", "drain", "drama", "drawn", "dream", "dress", "drift",
    "drink", "drive", "eager", "early", "earth", "eight", "elite", "empty",
    "enemy", "enjoy", "enter", "equal", "error", "event", "every", "exact",
    "exist", "extra", "faith", "false", "fault", "favor", "fence", "fewer",
    "fiber", "field", "fifth", "fifty", "fight", "final", "first", "fixed",
    "flash", "fleet", "flesh", "float", "flood", "floor", "fluid", "focus",
    "force", "forth", "found", "frame", "fresh", "front", "fruit", "giant",
    "given", "glass", "globe", "going", "grace", "grade", "grain", "grand",
    "grant", "grass", "grave", "great", "green", "gross", "group", "grown",
    "guard", "guess", "guide", "happy", "heart", "heavy", "honor", "horse",
    "hotel", "house", "human", "ideal", "image", "index", "inner", "input",
    "issue", "joint", "judge", "juice", "knife", "knock", "known", "label",
    "large", "laser", "later", "laugh", "layer", "learn", "least", "leave",
    "legal", "level", "light", "limit", "local", "logic", "loose", "lover",
    "lower", "lucky", "lunch", "magic", "major", "maker", "manor", "march",
    "match", "maybe", "mayor", "media", "mercy", "metal", "meter", "might",
    "minor", "minus", "mixed", "model", "money", "month", "moral", "motor",
    "mount", "mouse", "mouth", "movie", "music", "named", "nerve", "never",
    "night", "noise", "north", "novel", "nurse", "occur", "ocean", "offer",
    "often", "order", "other", "outer", "owned", "owner", "paint", "panel",
    "paper", "party", "patch", "pause", "peace", "penny", "phase", "phone",
    "photo", "piano", "piece", "pilot", "pitch", "place", "plain", "plane",
    "plant", "plate", "plaza", "point", "pound", "power", "press", "price",
    "pride", "prime", "print", "prior", "prize", "proof", "proud", "prove",
    "queen", "quiet", "quite", "quote", "radio", "raise", "range", "rapid",
    "ratio", "reach", "ready", "refer", "reign", "relax", "reply", "rider",
    "rifle", "right", "rigid", "rival", "river", "robot", "rocky", "roman",
    "rough", "round", "route", "royal", "rural", "saint", "salad", "sauce",
    "scale", "scene", "scope", "score", "sense", "serve", "seven", "shade",
    "shaft", "shake", "shall", "shame", "shape", "share", "sharp", "sheet",
    "shelf", "shell", "shift", "shirt", "shock", "shoot", "shore", "short",
    "shout", "sight", "silly", "since", "sixth", "sixty", "skill", "sleep",
    "slice", "slide", "small", "smart", "smell", "smile", "smoke", "solar",
    "solid", "solve", "sorry", "sound", "south", "space", "spare", "speak",
    "speed", "spend", "spill", "split", "sport", "spray", "squad", "stack",
    "staff", "stage", "stake", "stand", "start", "state", "steam", "steel",
    "steep", "stick", "still", "stock", "stone", "store", "storm", "story",
    "stove", "strip", "stuck", "study", "stuff", "style", "sugar", "suite",
    "super", "swear", "sweep", "sweet", "swing", "sword", "table", "taste",
    "teach", "teeth", "thank", "theme", "thick", "thing", "think", "third",
    "throw", "tight", "tired", "title", "today", "total", "touch", "tough",
    "tower", "trace", "track", "trade", "trail", "train", "trait", "treat",
    "trend", "trial", "tribe", "trick", "troop", "truck", "truly", "trump",
    "trust", "truth", "twice", "twist", "uncle", "under", "union", "unite",
    "until", "upper", "upset", "urban", "usage", "usual", "valid", "value",
    "video", "virus", "visit", "vital", "vocal", "voice", "waste", "watch",
    "water", "wheel", "where", "which", "while", "white", "whole", "whose",
    "woman", "world", "worry", "worse", "worst", "worth", "would", "wound",
    "write", "wrong", "wrote", "yield", "young", "youth",
    "accept", "access", "across", "action", "active", "actual", "advice",
    "affair", "affect", "afford", "agency", "agenda", "almost", "always",
    "amount", "animal", "annual", "answer", "anyone", "anyway", "appeal",
    "appear", "around", "arrive", "artist", "assume", "attack", "attend",
    "august", "author", "battle", "beauty", "become", "before", "behind",
    "belong", "beside", "beyond", "bitter", "blanket", "border", "bother",
    "bottom", "branch", "breath", "bridge", "bright", "broken", "budget",
    "burden", "butter", "button", "camera", "cancel", "carbon", "career",
    "castle", "cattle", "caught", "center", "chance", "change", "charge",
    "chosen", "church", "circle", "closed", "closer", "coffee", "column",
    "combat", "common", "comply", "corner", "costly", "cotton", "couple",
    "course", "cousin", "create", "credit", "crisis", "custom", "damage",
    "danger", "dealer", "debate", "decade", "decide", "defeat", "defend",
    "define", "degree", "demand", "denial", "depend", "deputy", "desert",
    "design", "desire", "detail", "detect", "device", "devote", "differ",
    "dinner", "direct", "divide", "doctor", "domain", "double", "driven",
    "driver", "during", "easily", "eating", "editor", "effect", "effort",
    "eighth", "either", "eleven", "emerge", "empire", "enable", "ending",
    "energy", "engage", "engine", "enough", "ensure", "entire", "equity",
    "escape", "estate", "ethnic", "evolve", "exceed", "except", "expand",
    "expect", "expert", "export", "expose", "extend", "fabric", "factor",
    "fairly", "fallen", "family", "famous", "father", "fellow", "female",
    "figure", "finger", "finish", "flower", "flying", "follow", "forget",
    "formal", "former", "foster", "fourth", "freely", "freeze", "friend",
    "frozen", "future", "gained", "garden", "gather", "gender", "gentle",
    "global", "golden", "govern", "ground", "growth", "guilty", "guitar",
    "handle", "happen", "hardly", "health", "heaven", "height", "hereby",
    "hidden", "highly", "holder", "honest", "horror", "hunger", "hunter",
    "ignore", "impact", "import", "impose", "income", "indeed", "infant",
    "inform", "injury", "inning", "insist", "intact", "intend", "intent",
    "invest", "island", "itself", "junior", "jungle", "justice", "killer",
    "kindly", "knight", "ladder", "largely", "latest", "latter", "launch",
    "lawyer", "layout", "leader", "league", "lender", "lesson", "letter",
    "likely", "listen", "little", "living", "lovely", "mainly", "making",
    "manage", "manner", "margin", "marked", "market", "master", "matter",
    "medium", "member", "memory", "mental", "merely", "method", "middle",
    "mighty", "miller", "mirror", "mobile", "modern", "modest", "moment",
    "motion", "mostly", "murder", "museum", "mutual", "myself", "narrow",
    "nation", "nature", "nearby", "nearly", "neatly", "needed", "nicely",
    "nobody", "normal", "notice", "notion", "number", "object", "obtain",
    "occupy", "office", "online", "oppose", "option", "orange", "origin",
    "others", "outfit", "output", "parent", "partly", "patent", "people",
    "period", "permit", "person", "phrase", "planet", "player", "please",
    "plenty", "pocket", "poetry", "poison", "police", "policy", "prefer",
    "prison", "profit", "prompt", "proper", "proven", "public", "pursue",
    "puzzle", "racial", "random", "rarely", "rather", "rating", "reader",
    "really", "reason", "recall", "record", "reduce", "reform", "regard",
    "region", "reject", "relate", "relief", "remain", "remedy", "remote",
    "remove", "rental", "repair", "repeat", "report", "rescue", "resist",
    "resort", "result", "retail", "retain", "retire", "return", "reveal",
    "review", "revolt", "reward", "rhythm", "riding", "rising", "robust",
    "ruling", "rumor", "sacred", "safety", "sailor", "salary", "sample",
    "scared", "scheme", "school", "screen", "search", "season", "second",
    "secret", "sector", "secure", "select", "senior", "serial", "settle",
    "severe", "shadow", "shared", "shield", "should", "shower", "signal",
    "silver", "simple", "simply", "singer", "single", "sister", "slight",
    "slowly", "smooth", "social", "solely", "source", "speech", "spirit",
    "spread", "spring", "square", "stable", "status", "steady", "strain",
    "strand", "stream", "street", "stress", "strict", "strike", "string",
    "stripe", "stroke", "strong", "studio", "submit", "sudden", "suffer",
    "summer", "summit", "supply", "surely", "survey", "switch", "symbol",
    "system", "tackle", "talent", "target", "temple", "tenant", "tender",
    "terror", "thanks", "theirs", "thirty", "though", "thread", "threat",
    "throat", "throne", "thrown", "timber", "tissue", "tongue", "tonight",
    "treaty", "tribal", "tunnel", "twelve", "unique", "unless", "unlike",
    "unrest", "update", "useful", "valley", "vastly", "victim", "viewer",
    "virtue", "vision", "visual", "volume", "Walker", "warmth", "weapon",
    "weekly", "weight", "welfare", "widely", "window", "winner", "winter",
    "wisdom", "within", "wonder", "worker", "worthy", "writer",
]

HARD = [
    "abandon", "ability", "absence", "absolve", "abstain", "academy",
    "achieve", "acquire", "address", "adjourn", "admiral", "advance",
    "adverse", "affable", "afflict", "alcohol", "allegiance", "alliance",
    "alright", "ambiguity", "analogy", "analyze", "ancient", "anxiety",
    "applaud", "appoint", "approve", "aptitude", "aquarium", "archive",
    "arduous", "artisan", "assault", "attempt", "audible", "average",
    "balcony", "baptize", "baroque", "barrier", "basilisk", "battery",
    "beneath", "benign", "bicycle", "bizarre", "blatant", "bouquet",
    "boycott", "breadth", "brigade", "brittle", "broaden", "bruised",
    "buffalo", "buoyant", "bureaucracy", "cabinet", "caliber",
    "campaign", "capacity", "casualty", "catalyst", "category",
    "cautious", "ceremony", "champion", "chandelier", "chronicle",
    "circuitry", "civilian", "coalesce", "cognitive", "coherent",
    "collapse", "collision", "combustion", "committee", "companion",
    "competent", "complexion", "compliant", "component", "composite",
    "compulsory", "concealed", "conceptual", "conducive", "confiscate",
    "congenial", "conjugate", "conscript", "consensus", "construct",
    "contagious", "contemplate", "contiguous", "continuum", "contradict",
    "controversy", "conundrum", "convalesce", "cooperate", "copyright",
    "corrugated", "courageous", "courteous", "craftsman", "crescendo",
    "criterion", "culminate", "cultivate", "cumbersome", "curriculum",
    "cynicism", "deceptive", "decibel", "decipher", "decompose",
    "defendant", "deficient", "deliberate", "delicately", "democracy",
    "demonstrate", "departure", "depreciate", "descendant", "desperate",
    "determine", "detriment", "devastate", "diagnosis", "diaphragm",
    "dichotomy", "diligence", "dimension", "dinosaur", "diplomacy",
    "disappoint", "discipline", "discourse", "discovery", "dismantle",
    "disparage", "dissipate", "distinguish", "diversify", "elaborate",
    "eloquence", "elsewhere", "embarrass", "emphasize", "empirical",
    "encompass", "encounter", "encourage", "endeavour", "enumerate",
    "ephemeral", "equipment", "equivalent", "establish", "estranged",
    "etymology", "euphemism", "evaporate", "evolution", "exacerbate",
    "exaggerate", "exasperate", "exceedingly", "exquisite", "extravagant",
    "fabricate", "fahrenheit", "fascinate", "fiduciary", "fluctuate",
    "fluorescent", "forbearance", "formidable", "fortuitous", "franchise",
    "fraternity", "frivolous", "fulfillment", "galvanize", "garrulous",
    "genealogy", "genuinely", "gestation", "glamorous", "governance",
    "gratitude", "gregarious", "grotesque", "guarantee", "gymnasium",
    "hallucinate", "handkerchief", "harassment", "harmonious", "hazardous",
    "hemorrhage", "hereditary", "hibernate", "hierarchy", "hitchhike",
    "homogeneous", "humiliate", "hurricane", "hydraulic", "hyperbole",
    "hypocrite", "hypothesis", "idiosyncrasy", "illegitimate", "illuminate",
    "illustrate", "immaculate", "immediately", "impeccable", "implication",
    "improvise", "inaugurate", "incandescent", "inconceivable", "indictment",
    "indigenous", "indispensable", "infrastructure", "innocuous",
    "innovation", "inoculate", "insufferable", "intelligence", "intercept",
    "interrogate", "intoxicate", "intrinsic", "iridescent", "irrelevant",
    "itinerary", "jeopardize", "journalism", "juxtapose", "kaleidoscope",
    "khaki", "labyrinth", "lackluster", "legitimate", "lieutenant",
    "liquidate", "longevity", "ludicrous", "luminescent", "luxurious",
    "magnificent", "maintenance", "malevolent", "maneuver", "manipulate",
    "manufacture", "manuscript", "masquerade", "meander", "melancholy",
    "metamorphosis", "meticulous", "microscope", "millennium", "miscellaneous",
    "mischievous", "misdemeanor", "monopolize", "monotonous", "moustache",
    "mnemonic", "mystique", "nauseous", "necessary", "negligible",
    "negotiate", "nonchalant", "nonetheless", "nostalgia", "nuisance",
    "obedience", "obligation", "obnoxious", "obscure", "observatory",
    "obstinate", "occasionally", "omniscient", "onomatopoeia", "opaque",
    "opportunity", "orchestrate", "ostracize", "outrageous", "overwhelm",
    "pageantry", "palindrome", "panoramic", "parachute", "paradox",
    "paraphernalia", "parliament", "particular", "patronize", "peculiar",
    "pedestrian", "peripheral", "perpetuate", "perseverance", "pessimism",
    "pharmaceutical", "phenomenon", "philanthropy", "picturesque",
    "plagiarize", "plausible", "pneumonia", "poignant", "posthumous",
    "precedent", "prejudice", "preposterous", "prerequisite", "prevalent",
    "privilege", "procrastinate", "propaganda", "psychology", "punctual",
    "quarantine", "questionnaire", "quintessential", "rambunctious",
    "reconnaissance", "reconcile", "referendum", "reminiscence",
    "remunerate", "rendezvous", "repertoire", "reprehensible",
    "resplendent", "resuscitate", "reverberate", "rhetorical",
    "sacrilegious", "sandwiched", "sarcasm", "saxophone", "scrupulous",
    "seismograph", "silhouette", "simultaneous", "skepticism",
    "sophisticated", "sovereignty", "spaghetti", "spontaneous",
    "stethoscope", "straightforward", "subconscious", "subsequent",
    "substantially", "subterfuge", "surveillance", "susceptible",
    "sympathize", "synchronize", "temperament", "therapeutic",
    "thermometer", "thorough", "threshold", "topography",
    "totalitarian", "tournament", "trajectory", "tranquility",
    "treacherous", "tremendous", "trespassing", "triumphant",
    "tyrannical", "ubiquitous", "unanimously", "unbelievable",
    "underestimate", "unfortunately", "unnecessary", "unprecedented",
    "unquestionable", "upholstery", "vaccination", "ventriloquist",
    "vocabulary", "vulnerable", "wheelbarrow", "whisper",
    "xylophone", "yesterday", "zealous",
]

DIFFICULTIES = {"easy": EASY, "medium": MEDIUM, "hard": HARD}


def generate(count=80, difficulty="medium"):
    pool = DIFFICULTIES.get(difficulty, MEDIUM)
    return " ".join(random.choice(pool) for _ in range(count))
